# Generated by Django 5.0.7 on 2024-07-28 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authpanel', '0002_alter_user_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_status',
            field=models.SmallIntegerField(choices=[(0, 'Inactive'), (1, 'Active'), (2, 'Deleted'), (3, 'Suspended')], default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='online_status',
            field=models.SmallIntegerField(choices=[(0, 'Offline'), (1, 'Online'), (2, 'Idle'), (3, 'Do Not Disturb'), (4, 'Invisible')], default=0),
        ),
    ]
